### ISSUE TITLE
Issue with OTP 21: Can't compile dependency ranch_proxy_protocol

### ISSUE THREAD

**Issue by stoicAlchemist** [pma/amqp#99] opened 2018-07-08 17:43 UTC
Didn't find an issue with same info so here it goes, I'm learning Elixir and RabbidMQ and from the RabbitMQ site, they suggest using this library. Following the first steps (adding it as a dependency and running the iex -S mix command, just yields an error like so:

`** (Mix) Could not compile dependency :ranch_proxy_protocol, "/Users/brianmartinez/.mix/rebar3 bare compile --paths "/Users/brianmartinez/Elixir/rabbit
mq_tutorials/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile ranch_proxy_protocol", update it with "mi
x deps.update ranch_proxy_protocol" or clean it with "mix deps.clean ranch_proxy_protocol"
`
Already attempted the clean, update and compile suggestions but it's still the same, any thoughts?

**Comment by stoicAlchemist** [comment] 2018-07-09 00:35
I think the issue is that the dependencies on the `mix.exs` file don't reflect the lock file, so whenever a new project requires yours, it creates a new lock file with the old versions. I've created the PR, please correct me if I'm wrong: https://github.com/pma/amqp/pull/100

**Comment by stuartbain** [comment] 2018-07-13 07:32
@stoicAlchemist Unfortunately updating ranch and ranch_proxy_protocol to 1.5 didn't fix the compile error for me.

**Comment by ono** [comment] 2018-07-13 08:22
A few requests and questions:

- Can you upload a sample project that reproduces the error as your public git repo please?
- What happens if you compile amqp library itself? Does it give you an error? [*1]
- Can you describe your local environment? OS, OTP version and Elixir version?

[*1]
```
% git clone https://github.com/pma/amqp.git
% cd amqp
% mix deps.get
% mix compile
```

**Comment by stuartbain** [comment] 2018-07-13 09:19
I was able to fix the issue by using the Github master branch of ranch_proxy_protocol in my mix.exs file as follows.

`{:ranch_proxy_protocol, github: "heroku/ranch_proxy_protocol", override: true}`

It looks like the problem is due to OTP 21 deprecating the ssl:ssl_accept with the ssl:accept function.

There is a issue raised to publish a new version to hex.pm here: [please update hex.pm to support OTP 21](https://github.com/heroku/ranch_proxy_protocol/issues/43)

**Comment by stuartbain** [comment] 2018-07-13 09:30
It appears that there is an issue with OTP 21 and ranch_proxy_protocol due to the deprecation of ssl:ssl_accept by ssl:handshake

The problem has been fixed in the ranch_proxy_protocol master branch but there is an outstanding issue https://github.com/heroku/ranch_proxy_protocol/issues/43 to publish the change to hex.

In the meantime, I managed to successfully compile by adding the following line to my mix.exs file:

`{:ranch_proxy_protocol, github: "heroku/ranch_proxy_protocol", override: true}`

**Comment by stoicAlchemist** [comment] 2018-07-13 20:35
Sorry for the late response, I'm using the `mix new rabbitmq_tutorial` this creates a new proyect. The Elixir version is 1.6.6, OTP 21, I'm doing this on a Mac OSX 10.13.5 High Sierra. The attempt to compile the library is not successful:

```
amqp (git)-[master] >>> mix compile                                                            (0) [0] 15:34:12
===> Compiling ranch
src/ranch_ssl.erl:131: Warning: ssl:ssl_accept/2: deprecated; use ssl:handshake/2 instead

===> Compiling ranch_proxy_protocol
===> Compiling src/ranch_proxy_ssl.erl failed
src/ranch_proxy_ssl.erl:90: ssl:ssl_accept/3: deprecated; use ssl:handshake/3 instead

** (Mix) Could not compile dependency :ranch_proxy_protocol, "/Users/brianmartinez/.mix/rebar3 bare compile --paths "/Users/brianmartinez/Elixir/amqp/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile ranch_proxy_protocol", update it with "mix deps.update ranch_proxy_protocol" or clean it with "mix deps.clean ranch_proxy_protocol"
```
I'll take a look to the OTP issue to see if there is anything I can do to help.

**Comment by ono** [comment] 2018-07-13 21:49
Thanks! Set up CI with OTP 21 [here](https://github.com/pma/amqp/pull/101) and managed to reproduce the error [here](https://travis-ci.org/pma/amqp/jobs/403743288).

For time being, let's follow @stuartbain's workaround(thanks for sharing!) and wait for ranch_proxy_protocol to release a new version.

**Comment by stuartbain** [comment] 2018-07-14 07:46
ranch_proxy_protocol 2.0.0 has been released and amqp compiles with the following override in mix.exs:

`{:ranch_proxy_protocol, "~> 2.0", override: true}`

**Comment by ono** [comment] 2018-07-14 08:19
https://github.com/rabbitmq/rabbitmq-common/issues/269

Once they have updated the dependency we will accommodate the change.

**Comment by steffkes** [comment] 2018-09-13 13:13
Just FYI, it's done: https://github.com/rabbitmq/rabbitmq-common/issues/269 (and https://github.com/heroku/ranch_proxy_protocol/pull/49) got merged

**Comment by ono** [comment] 2018-09-13 13:17
@steffkes great. thanks for the heads up. I will chase it up in this week 👍

**Comment by ono** [comment] 2018-09-16 17:50
It's reopened again https://github.com/rabbitmq/rabbitmq-common/issues/269 but the fix will be coming soon.

**Comment by hats** [comment] 2018-10-08 10:09
This deps versions works for me:
```elixir
      {:amqp_client, "~> 3.7.8", override: true},
      {:rabbit_common, "~> 3.7.8", override: true},
      {:ranch, "~> 1.6.2", override: true},
      {:ranch_proxy_protocol, "~> 2.1.1", override: true},
      {:lager, "~> 3.6.6", override: true},
```

**Comment by Relrin** [comment] 2018-11-27 14:12
@ono Do you have any plans for updating and releasing a new version of this package? As far as I concerned, the `ranch_proxy_protocol` and `rabbit_common ` packages have updated recently. It will great to see the release of `amqp` as well :)

**Comment by ono** [comment] 2018-11-27 21:08
OK guys. [1.1.0](https://hex.pm/packages/amqp/1.1.0) is out with amqp_client/rabbit_common 3.7.9 which is officially compatible with OTP 21. :tada:

**Closed by ono** 2018-11-27 21:08 UTC
